# BetterClaim Configuration File
# For support, visit: https://github.com/fliuxx/BetterClaim

# Database settings
database:
  type: sqlite
  filename: claims.db
  
# Claim settings
claim:
  # Maximum number of chunks per claim
  max-chunks-per-claim: 100
  # Maximum number of claims per player
  max-claims-per-player: 1
  # Require claims to be adjacent (expandable only)
  require-adjacent: true
  # Show claim borders when entering/leaving
  show-borders: true
  # Border particle effect
  border-particle: REDSTONE
  # Auto-save interval in minutes
  auto-save-interval: 5
  
# Default claim flags
default-flags:
  pvp: false
  mob-spawning: true
  mob-damage: true
  explosions: false
  fire-spread: false
  lava-flow: false
  water-flow: true
  item-pickup: false
  block-break: false
  block-place: false
  container-access: false
  door-access: false
  button-access: false
  lever-access: false
  pressure-plate-access: false
  redstone-access: false
  entity-interact: false
  animal-damage: false
  
# Trust levels and their permissions
trust-levels:
  trusted:
    - block-break
    - block-place
    - container-access
    - door-access
    - button-access
    - lever-access
    - item-pickup
  moderator:
    - block-break
    - block-place
    - container-access
    - door-access
    - button-access
    - lever-access
    - pressure-plate-access
    - redstone-access
    - entity-interact
    - item-pickup
  admin:
    - block-break
    - block-place
    - container-access
    - door-access
    - button-access
    - lever-access
    - pressure-plate-access
    - redstone-access
    - entity-interact
    - animal-damage
    - item-pickup
    
# GUI settings
gui:
  # GUI title prefixes
  titles:
    claim-main: "&6&lClaim Management"
    claim-flags: "&6&lClaim Flags"
    claim-trust: "&6&lClaim Trust"
    admin-main: "&c&lAdmin Panel"
    
# Performance settings
performance:
  # Cache size for claims
  cache-size: 1000
  # Cache expiration time in minutes
  cache-expiration: 30
  # Async operations
  async-saves: true
